name: PieRay
version: 'BETA'
main: io.github.moregrayner.pieRay.PieRay
api-version: '1.21'
authors: [ 짱레인 ]
description: 벡터기반 엑스레이 탐지 플러그인
commands:
  pieray:
    description: PieRay main command
    usage: /pieray <scan|list|reload>
    permission: pieray.admin

permissions:
  pieray.admin:
    description: Access to all PieRay commands
    default: op